[package]
name = "github-profile-stats-rs"
description = "generate pretty svgs for your profile on GitHub"
version = "0.1.0"
edition = "2024"

[dependencies]
async-scoped = { version = "0.9.0", features = ["tokio"] }
camino = "1.2.2"
clap = { version = "^4.0", features = ["derive"] }
color-eyre = { version = "0.6.5", default-features = false }
derive_typst_intoval = "0.6.0"
futures = "0.3.31"
indicatif = { version = "0.18.3", features = ["tokio"] }
octocrab = "0.49.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.18", default-features = false }
typst = "0.14.2"
typst-as-lib = { version = "0.15.1", features = ["packages", "reqwest"] }
typst-library = "0.14.2"
typst-svg = "0.14.2"
