[package]
name = "skrytsam"
description = "generate pretty svgs for your profile on GitHub"
version = "0.1.4"
edition = "2024"
repository = "https://github.com/sermuns/skrytsam"
license = "WTFPL"

[dependencies]
clap = { version = "4", features = ["derive"] }
color-eyre = { version = "0.6.5", default-features = false }
derive_typst_intoval = "0.6.0"
futures = "0.3.31"
indicatif = { version = "0.18.3", features = ["tokio"] }
octocrab = "0.49.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
typst = "0.14.2"
typst-as-lib = { version = "0.15.4", features = ["packages", "ureq"] }
typst-library = "0.14.2"
typst-svg = "0.14.2"

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1
strip = true
