name: CD
on:
  push:
    tags:
      - "*"

env:
  CRATE_NAME: skrytsam

jobs:
  github_build:
    name: build release binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: x86_64-unknown-linux-gnu.tar.gz

          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: x86_64-unknown-linux-musl.tar.gz

          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            name: aarch64-unknown-linux-musl.tar.gz

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2

      - name: build
        if: ${{ !endsWith(matrix.target, '-unknown-linux-musl') }}
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - if: endsWith(matrix.target, '-unknown-linux-musl')
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: build (musl)
        if: endsWith(matrix.target, '-unknown-linux-musl')
        run: cross build --verbose --release --target ${{ matrix.target }}

      - name: extract tag
        shell: bash
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        id: extract_tag

      - name: prepare artifacts
        run: |
          mkdir -p target/stage
          cd target/${{ matrix.target }}/release
          tar czvf ../../stage/${{ env.CRATE_NAME }}-${{ steps.extract_tag.outputs.tag }}-${{ matrix.name }} ${{ env.CRATE_NAME }}

      - name: upload artifacs
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.CRATE_NAME }}-${{ steps.extract_tag.outputs.tag }}-${{ matrix.name }}
          path: target/stage/*
          overwrite: true

  github_release:
    name: create github release
    needs: github_build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v7
        with:
          path: artifacts

      - run: tree

      - name: extract version
        shell: bash
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        id: extract_version

      - name: write release notes
        run: |
          sed -n '/^## \[${{ steps.extract_version.outputs.version }}\].*$/,/^## /p' CHANGELOG.md | sed '$d' > RELEASE.md

      - name: publish
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
          body_path: RELEASE.md
          fails_on_unmatched_files: true
